server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
  servlet:
    context-path: /ontop

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  datasource:
    url: jdbc:h2:${H2_DATABASE_URL:mem:ontop}
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

ontop:
  account:
    account-name: ${ONTOP_ACCOUNT_NAME:ONTOP INC}
    account-number: ${ONTOP_ACCOUNT_NO:0245253419}
    routing-number: ${ONTOP_ROUTING_NUMBER:028444018}
  payment:
    max-retries: 2
    retry-delay-factor-seconds: 5

jdbc:
  lock:
    release-time-seconds: 30

client:
    host: ${CLIENT_HOST:http://mockoon.tools.getontop.com:3000}
    connection-timeout-ms: 10000
    read-timeout-ms: 10000
